//search form
export const SET_EMAIL_PROPERTIES = '[SEARCH_FORM] SET_EMAIL_PROPERTIES';
export const SET_CREDIT_FIRST_PROPERTIES = '[SEARCH_FORM] SET_CREDIT_FIRST_PROPERTIES';
export const SET_CREDIT_LAST_PROPERTIES = '[SEARCH_FORM] SET_CREDIT_LAST_PROPERTIES';
export const SET_USERNAME_PROPERTIES = '[SEARCH_FORM] SET_USERNAME_PROPERTIES';
export const SET_FIRST_NAME_PROPERTIES = '[SEARCH_FORM] SET_FIRST_NAME_PROPERTIES';
export const SET_LAST_NAME_PROPERTIES = '[SEARCH_FORM] SET_LAST_NAME_PROPERTIES';
export const SET_TRANSACTION_START_PROPERTIES = '[SEARCH_FORM] SET_TRANSACTION_START_PROPERTIES';
export const SET_TRANSACTION_END_PROPERTIES = '[SEARCH_FORM] SET_TRANSACTION_END_PROPERTIES';
export const SET_PRO_MEM_ID_PROPERTIES = '[SEARCH_FORM] SET_PRO_MEM_ID_PROPERTIES';
export const SET_PRO_TRAN_ID_PROPERTIES = '[SEARCH_FORM] SET_PRO_TRAN_ID_PROPERTIES';
export const SET_BILLER_MEM_ID_PROPERTIES = '[SEARCH_FORM] SET_BILLER_MEM_ID_PROPERTIES';
export const SET_BILLER_TRAN_ID_PROPERTIES = '[SEARCH_FORM] SET_BILLER_TRAN_ID_PROPERTIES';
export const SET_PRO_SUB_ID_PROPERTIES = '[SEARCH_FORM] SET_PRO_SUB_ID_PROPERTIES';
